# Generated by Django 6.0.4 on 2026-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participation achat groupé',
                'db_table': 'group_buy_participations',
            },
        ),
        migrations.CreateModel(
            name='GroupBuySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('threshold_reached', 'Seuil atteint'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Complété')], default='open', max_length=20)),
                ('target_quantity', models.PositiveIntegerField(verbose_name='Quantité cible (seuil de gros)')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité actuelle')),
                ('unit_price_at_bulk', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire de gros (FCFA)')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Session d'achat groupé",
                'verbose_name_plural': "Sessions d'achat groupé",
                'db_table': 'group_buy_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('individual', 'Individuel'), ('group', 'Achat groupé')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total (FCFA)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Commission (FCFA)')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Ville de livraison')),
                ('delivery_district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('delivery_landmark', models.CharField(blank=True, max_length=255, verbose_name='Repère géographique')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='Téléphone de livraison')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence commande')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Sous-total (FCFA)')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'db_table': 'order_items',
            },
        ),
    ]
