# Generated by Django 6.0.4 on 2026-04-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Événement')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(default=dict, verbose_name="Données de l'événement")),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal audit paiement',
                'verbose_name_plural': 'Journaux audit paiements',
                'db_table': 'payment_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde (FCFA)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total gagné (FCFA)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total retiré (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portefeuille vendeur',
                'db_table': 'vendor_wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant demandé (FCFA)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'db_table': 'withdrawal_requests',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=20, verbose_name='Opérateur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('currency', models.CharField(default='XOF', max_length=5, verbose_name='Devise')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID Transaction')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence opérateur')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro payeur')),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente de confirmation'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='initiated', max_length=20)),
                ('status_message', models.TextField(blank=True, verbose_name='Message statut opérateur')),
                ('raw_request', models.JSONField(default=dict, verbose_name='Requête brute envoyée')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Réponse brute reçue')),
                ('webhook_payload', models.JSONField(blank=True, null=True, verbose_name='Payload webhook reçu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
