# Generated by Django 6.0.4 on 2026-04-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis produit',
                'db_table': 'product_reviews',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (emoji ou classe CSS)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de gros (FCFA)')),
                ('bulk_min_quantity', models.PositiveIntegerField(default=10, verbose_name='Quantité min. pour le prix de gros')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('unit', models.CharField(default='unité', max_length=30, verbose_name='Unité de mesure')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Poids (kg)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('out_of_stock', 'Rupture de stock')], default='draft', max_length=20)),
                ('is_essential', models.BooleanField(default=False, help_text='Produits prioritaires pour la stabilisation des prix', verbose_name='Produit de première nécessité')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbs/', verbose_name='Miniature')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Image principale')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
